##' @title Combine hourly data
##' @param comps list of components of hourly energy generated by
##' \code{\link{get.inf.data.hourly}}.
##' @param tot Total energy generated by \code{\link{get.uni.data.hourly}} 
##' @return data frame with class \code{hourly} containing the
##' components and the residual Other energy use
##' @author David Sterratt
##' @export
combine.data.hourly <- function(comps=list(), tot=NA) {
  if (!any(is.na(tot))) {
    dat <- data.frame(Time=tot[,"Time"])
    other <- tot$kWh
  } else {
    dat <- data.frame(Time=comps[[1]][,"Time"])
  }
  for (n in names(comps)) {
    comp <- comps[[n]]
    if (!any(is.na(tot))) {
      if (attr(comp, "from") != attr(tot, "from")) {
        stop(paste("From date of ", n, "component doesn't match from date of total"))
      }
      if (attr(comp, "to") != attr(tot, "to")) {
        stop(paste("To date of", n, "component doesn't match to date of total"))
      }
      other <- other - comp$kWh      
    }
    col <- data.frame(comp$kWh)
    colnames(col) <- n
    dat <- data.frame(dat, col)
  }
  if (!any(is.na(tot))) {
    dat <- data.frame(dat, Other=other)
    attr(dat, "from") <- attr(tot, "from")
    attr(dat, "to")   <- attr(tot, "to")
  } else  {
    attr(dat, "from") <- attr(comps[[1]], "from")
    attr(dat, "to")   <- attr(comps[[1]], "to")
  }
  class(dat) <- c("hourly", "data.frame")
  return(dat)
}

