##' @title Combine hourly data
##' @param comps list of components of hourly energy generated by
##' \code{\link{get.inf.data.hourly}}.
##' @param tot Total energy generated by \code{\link{get.uni.data.hourly}} 
##' @return data frame with class \code{hourly} containing the
##' components and the residual Other energy use
##' @author David Sterratt
##' @export
combine.data.hourly <- function(comps=list(), tot) {
  dat <- data.frame(Time=tot[,"Time"])
  other <- tot$kWh
  for (n in names(comps)) {
    comp <- comps[[n]]
    if (attr(comp, "from") != attr(tot, "from")) {
      stop(paste("From date of ", n, "component doesn't match from date of total"))
    }
    if (attr(comp, "to") != attr(tot, "to")) {
      stop(paste("To date of", n, "component doesn't match to date of total"))
    }
    other <- other - comp$kWh
    col <- data.frame(comp$kWh)
    colnames(col) <- n
    dat <- data.frame(dat, col)
  }
  dat <- data.frame(dat, Other=other)
  attr(dat, "from") <- attr(tot, "from")
  attr(dat, "to")   <- attr(tot, "to")
  class(dat) <- c("hourly", "data.frame")
  return(dat)
}
